const ferramentas = [
    {
        titulo: "Notion",
        descricao: "Uma plataforma versátil para organização de notas, gerenciamento de tarefas e planejamento colaborativo. Oferece uma interface intuitiva e personalizável para manter todas as suas informações em um só lugar.",
        tags: ["Organização", "Produtividade", "Colaboração", "Planejamento", "Gerenciamento de Tarefas"],
        link: "https://www.notion.so",
        dificuldade: "Médio",
        preco: "Freemium",
        plataformas: ["Web", "Windows", "Mac", "iOS", "Android"],
        popularidade: "4.5/5",
        licenca: "Proprietária"
    },
    {
        titulo: "Perplexity",
        descricao: "Perplexity é um motor de busca e assistente de pesquisa baseado em inteligência artificial, que fornece respostas em tempo real a perguntas complexas, utilizando processamento de linguagem natural para entender e gerar texto.",
        tags: ["IA", "Busca", "Análise de Dados", "Previsão", "Inteligência Artificial"],
        link: "https://perplexity.ai",
        dificuldade: "Médio",
        preco: "Freemium",
        plataformas: ["Web", "iOS", "Android"],
        popularidade: "4.3/5",
        licenca: "Proprietária"
    },
    {
        titulo: "Feels App",
        descricao: "Feels é um aplicativo que ajuda os usuários a monitorar e entender suas emoções, promovendo o bem-estar mental. Através de registros diários, os usuários podem identificar padrões emocionais e receber dicas personalizadas para melhorar sua saúde mental.",
        tags: ["Saúde Mental", "Bem-estar", "Análise de Emoções", "Bem-estar"],
        link: "https://f-droid.org/packages/com.feels.feelingsApp.feels_app/",
        dificuldade: "Fácil",
        preco: "Freemium",
        plataformas: ["Android"],
        popularidade: "4.4/5",
        licenca: "Proprietária"
    },
    {
        titulo: "MyFitnessPal",
        descricao: "MyFitnessPal é um aplicativo de monitoramento de refeições que ajuda os usuários a acompanhar suas calorias e nutrientes, promovendo hábitos alimentares saudáveis e ajudando a alcançar metas de saúde, como perda de peso e tonificação do corpo.",
        tags: ["Saúde", "Fitness", "Nutrição", "Alimentação", "Rastreamento de Atividades"],
        link: "https://www.myfitnesspal.com",
        dificuldade: "Fácil",
        preco: "Freemium",
        plataformas: ["Web", "iOS", "Android"],
        popularidade: "4.7/5",
        licenca: "Proprietária"
    },
    {
        titulo: "Microsoft Launcher",
        descricao: "Personalize a tela inicial do seu dispositivo Android com o Microsoft Launcher, que oferece uma experiência de usuário otimizada, integração com o Microsoft 365 e funcionalidades para organizar seu dia a dia.",
        tags: ["Personalização", "Produtividade", "Integração", "Microsoft 365", "Organização"],
        link: "https://play.google.com/store/apps/details?id=com.microsoft.launcher&hl=en_US",
        dificuldade: "Fácil",
        preco: "Gratuito",
        plataformas: ["Android"],
        popularidade: "4.5/5",
        licenca: "Proprietária"
    },
    {
        titulo: "Bitwarden",
        descricao: "Um gerenciador de senhas robusto e seguro que ajuda a armazenar e gerar senhas complexas, com funcionalidades de criptografia de ponta a ponta para proteger suas informações sensíveis.",
        tags: ["Segurança", "Senhas", "Gerenciamento de Senhas", "Criptografia", "Privacidade"],
        link: "https://bitwarden.com",
        dificuldade: "Fácil",
        preco: "Gratuito",
        plataformas: ["Web", "Windows", "Mac", "Linux", "iOS", "Android"],
        popularidade: "4.8/5",
        licenca: "Proprietária"
    },
    {
        titulo: "Ente Auth",
        descricao: "Ferramenta especializada em autenticação de dois fatores (2FA), fornecendo uma camada adicional de segurança para suas contas online através de códigos temporários e verificação em duas etapas.",
        tags: ["Segurança", "Autenticação", "2FA", "Privacidade", "Proteção de Contas"],
        link: "https://ente.io/blog/auth/",
        dificuldade: "Médio",
        preco: "Freemium",
        plataformas: ["Web", "Windows", "Mac", "Linux", "iOS", "Android"],
        popularidade: "4.2/5",
        licenca: "Open-source"
    },
    {
        titulo: "Local Send",
        descricao: "Permite o envio seguro e rápido de arquivos entre dispositivos conectados à mesma rede local, ideal para compartilhamento direto e rápido.",
        tags: ["Compartilhamento de Arquivos", "Transferência Local", "Segurança", "Rede", "Produtividade"],
        link: "https://localsend.org/download",
        dificuldade: "Fácil",
        preco: "Gratuito",
        plataformas: ["Windows", "Mac", "Linux", "iOS", "Android"],
        popularidade: "4.1/5",
        licenca: "Open-source"
    },
    {
        titulo: "Mind Meister",
        descricao: "Ferramenta para criação de mapas mentais que facilita a organização de ideias, planejamento de projetos e brainstorms colaborativos, com uma interface intuitiva e recursos de compartilhamento.",
        tags: ["Mapas Mentais", "Organização", "Brainstorming", "Planejamento", "Colaboração"],
        link: "https://www.mindmeister.com",
        dificuldade: "Médio",
        preco: "Freemium",
        plataformas: ["Web", "iOS", "Android"],
        popularidade: "4.4/5",
        licenca: "Proprietária"
    },
    {
        titulo: "Cabeceira",
        descricao: "Aplicativo para leitura e audição de livros, oferecendo resumos e conteúdos adicionais para que você possa ler mais livros e expandir seu conhecimento de maneira prática.",
        tags: ["Leitura", "Audiolivros", "Resumos", "Aprendizado", "Conhecimento"],
        link: "https://apps.apple.com/br/app/cabeceira-leia-mais-livros/id1481633011",
        dificuldade: "Fácil",
        preco: "Freemium",
        plataformas: ["iOS", "Android"],
        popularidade: "4.2/5",
        licenca: "Proprietária"
    },
    {
        titulo: "Google Lens",
        descricao: "Aplicativo de reconhecimento de imagem que permite buscar informações sobre objetos, textos e imagens através da câmera do seu dispositivo, oferecendo resultados baseados em visão computacional.",
        tags: ["Reconhecimento de Imagem", "IA", "Busca Visual", "Realidade Aumentada", "Tradução"],
        link: "https://lens.google",
        dificuldade: "Fácil",
        preco: "Gratuito",
        plataformas: ["Web", "iOS", "Android"],
        popularidade: "4.5/5",
        licenca: "Proprietária"
    },
    {
        titulo: "CapCut",
        descricao: "Editor de vídeo desenvolvido pela ByteDance, que oferece uma ampla gama de ferramentas de edição, efeitos e transições para criar vídeos de alta qualidade diretamente do seu celular.",
        tags: ["Edição de Vídeo", "Criação de Conteúdo", "Redes Sociais", "Multimídia", "Criatividade"],
        link: "https://www.capcut.com",
        dificuldade: "Fácil",
        preco: "Gratuito",
        plataformas: ["Web", "Windows", "Mac", "iOS", "Android"],
        popularidade: "4.6/5",
        licenca: "Proprietária"
    },
    {
        titulo: "1Password",
        descricao: "Gerenciador de senhas que oferece armazenamento seguro e fácil acesso a suas senhas e dados confidenciais, com recursos de geração de senhas e sincronização entre dispositivos.",
        tags: ["Segurança", "Senhas", "Gerenciamento de Senhas", "Privacidade", "Sincronização"],
        link: "https://1password.com",
        dificuldade: "Fácil",
        preco: "Freemium",
        plataformas: ["Web", "Windows", "Mac", "Linux", "iOS", "Android"],
        popularidade: "4.8/5",
        licenca: "Proprietária"
    },
    {
        titulo: "ChatGPT",
        descricao: "ChatGPT é um modelo de linguagem avançado desenvolvido pela OpenAI. Ele é projetado para gerar texto e responder a perguntas em linguagem natural, oferecendo suporte em uma ampla gama de tópicos e áreas. Ideal para assistência personalizada e automação de atendimento.",
        tags: ["IA", "Assistente Virtual", "Chatbot", "Inteligência Artificial", "Linguagem Natural"],
        link: "https://chat.openai.com",
        dificuldade: "Fácil",
        preco: "Freemium",
        plataformas: ["Web", "iOS", "Android"],
        popularidade: "4.8/5",
        licenca: "Proprietária"
    },
    {
        titulo: "Duolingo",
        descricao: "Duolingo é um aplicativo de aprendizado de idiomas que gamifica o processo de aprendizagem com exercícios interativos e jogos. O app se adapta ao progresso do usuário e oferece uma forma envolvente e eficaz de aprender novos idiomas, com suporte para diversas línguas.",
        tags: ["Educação", "Idiomas", "Gamificação", "Aprendizado", "Línguas"],
        link: "https://www.duolingo.com",
        dificuldade: "Fácil",
        preco: "Gratuito",
        plataformas: ["Web", "Windows", "iOS", "Android"],
        popularidade: "4.7/5",
        licenca: "Proprietária"
    },
    {
        titulo: "Figma",
        descricao: "Figma é uma ferramenta de design colaborativo e prototipagem de interfaces de usuário. Suporta trabalho em equipe em tempo real e oferece uma vasta gama de recursos de design e prototipagem. Ideal para designers que necessitam de uma solução integrada e colaborativa para criar layouts e protótipos interativos.",
        tags: ["Design", "Prototipagem", "Colaboração", "UI/UX", "Design de Interface"],
        link: "https://www.figma.com",
        dificuldade: "Médio",
        preco: "Freemium",
        plataformas: ["Web", "Windows", "Mac", "iOS", "Android"],
        popularidade: "4.9/5",
        licenca: "Proprietária"
    },
    {
        titulo: "Canva",
        descricao: "Canva é uma plataforma de design gráfico que simplifica a criação de material visual, como posts em redes sociais, apresentações e outros conteúdos gráficos. Oferece uma interface intuitiva e uma vasta biblioteca de templates e recursos que facilitam o design para usuários de todos os níveis.",
        tags: ["Design", "Gráficos", "Criatividade", "Templates", "Design Gráfico"],
        link: "https://www.canva.com",
        dificuldade: "Fácil",
        preco: "Gratuito",
        plataformas: ["Web", "Windows", "Mac", "iOS", "Android"],
        popularidade: "4.4/5",
        licenca: "Proprietária"
    },
    {
        titulo: "Slack",
        descricao: "Slack é uma ferramenta de comunicação e colaboração para equipes que oferece canais organizados, mensagens instantâneas e integrações com diversas outras ferramentas. Facilita a coordenação de projetos e melhora a eficiência do fluxo de trabalho com recursos de comunicação centralizados.",
        tags: ["Comunicação", "Colaboração", "Produtividade", "Mensagens", "Comunicação em Equipe"],
        link: "https://slack.com",
        dificuldade: "Médio",
        preco: "Freemium",
        plataformas: ["Web", "Windows", "Mac", "Linux", "iOS", "Android"],
        popularidade: "4.3/5",
        licenca: "Proprietária"
    },
    {
        titulo: "Google Drive",
        descricao: "Google Drive é um serviço de armazenamento em nuvem que permite a criação, compartilhamento e colaboração em documentos e arquivos. Integrado com outras ferramentas do Google, oferece uma solução robusta para gerenciamento de arquivos e sincronização entre dispositivos.",
        tags: ["Armazenamento", "Nuvem", "Colaboração", "Sincronização", "Gerenciamento de Arquivos"],
        link: "https://drive.google.com",
        dificuldade: "Fácil",
        preco: "Gratuito",
        plataformas: ["Web", "Windows", "Mac", "iOS", "Android"],
        popularidade: "4.6/5",
        licenca: "Proprietária"
    },
    {
        titulo: "GitHub",
        descricao: "GitHub é uma plataforma de hospedagem de código e controle de versão baseada em Git, voltada para desenvolvedores e equipes de desenvolvimento de software. Oferece recursos para versionamento, revisão de código e gerenciamento de projetos, facilitando a colaboração em projetos de software.",
        tags: ["Desenvolvimento", "Versionamento", "Colaboração", "Git", "Controle de Versão"],
        link: "https://github.com",
        dificuldade: "Médio",
        preco: "Freemium",
        plataformas: ["Web", "Windows", "Mac", "iOS", "Android"],
        popularidade: "4.8/5",
        licenca: "Open-source"
    },
    {
        titulo: "Google Analytics",
        descricao: "Google Analytics é uma ferramenta avançada para monitorar e analisar o tráfego e o comportamento dos visitantes em seu site. Ajuda a otimizar estratégias de marketing e melhorar a experiência do usuário por meio de relatórios detalhados e insights sobre o desempenho do site.",
        tags: ["Analytics", "SEO", "Marketing Digital", "Análise de Dados", "Otimização de Site"],
        link: "https://analytics.google.com",
        dificuldade: "Médio",
        preco: "Freemium",
        plataformas: ["Web"],
        popularidade: "4.5/5",
        licenca: "Proprietária"
    },
    {
        titulo: "Azure Data Studio",
        descricao: "Azure Data Studio é uma poderosa ferramenta de gerenciamento e desenvolvimento de banco de dados da Microsoft, ideal para SQL Server, Azure SQL Database e outros sistemas de banco de dados. Oferece uma interface moderna, suporte a extensões e funcionalidades avançadas como edição de código SQL, visualização de dados e integração com Git.",
        tags: ["Banco de Dados", "Desenvolvimento", "SQL", "Gerenciamento de Dados", "Visualização de Dados"],
        link: "https://learn.microsoft.com/pt-br/azure-data-studio/download-azure-data-studio?tabs=win-install%2Cwin-user-install%2Credhat-install%2Cwindows-uninstall%2Credhat-uninstall",
        dificuldade: "Médio",
        preco: "Gratuito",
        plataformas: ["Windows", "Mac", "Linux"],
        popularidade: "4.4/5",
        licenca: "Proprietária"
    },
    {
        titulo: "Cursor IDE",
        descricao: "Cursor IDE é uma plataforma de desenvolvimento integrada que utiliza inteligência artificial para acelerar o desenvolvimento de software. Oferece sugestões inteligentes de código, refatoração automática e auto-completar, ajudando os desenvolvedores a escrever código mais rápido e com menos erros.",
        tags: ["Desenvolvimento", "Inteligência Artificial", "IDE", "Desenvolvimento de Software", "Produtividade"],
        link: "https://www.cursor.com",
        dificuldade: "Médio",
        preco: "Freemium",
        plataformas: ["Web", "Windows", "Mac"],
        popularidade: "4.6/5",
        licenca: "Proprietária"
    },
    {
        titulo: "Brave",
        descricao: "Brave é um navegador web focado em privacidade e segurança, bloqueando rastreadores e anúncios invasivos por padrão. Ele também oferece uma navegação mais rápida e a opção de ganhar recompensas por visualizar anúncios opt-in, tudo enquanto protege seus dados e sua privacidade.",
        tags: ["Navegador", "Privacidade", "Segurança", "Bloqueador de Anúncios", "Proteção de Dados"],
        link: "https://brave.com",
        dificuldade: "Fácil",
        preco: "Gratuito",
        plataformas: ["Web", "Windows", "Mac", "Linux", "iOS", "Android"],
        popularidade: "4.7/5",
        licenca: "Open Source"
    },
    {
        titulo: "Concepts",
        descricao: "Concepts é uma ferramenta de design e esboço digital que oferece uma tela infinita para desenhar, criar e colaborar. É ideal para designers e artistas, proporcionando uma ampla gama de ferramentas e recursos para um fluxo criativo fluido e eficaz, com suporte para canetas e entrada de toque.",
        tags: ["Design", "Desenho", "Arte", "Colaboração", "Criatividade"],
        link: "https://concepts.app",
        dificuldade: "Médio",
        preco: "Freemium",
        plataformas: ["Web", "Windows", "Mac", "iOS", "Android"],
        popularidade: "4.5/5",
        licenca: "Proprietária"
    },
    {
        titulo: "Everything",
        descricao: "Everything é uma ferramenta de busca extremamente rápida para Windows que indexa arquivos e pastas em tempo real, permitindo encontrar qualquer coisa no seu sistema com uma rapidez impressionante. É ideal para quem precisa de uma solução de busca eficiente e leve.",
        tags: ["Busca", "Produtividade", "Utilitário", "Rapidez", "Indexação"],
        link: "https://www.voidtools.com",
        dificuldade: "Fácil",
        preco: "Gratuito",
        plataformas: ["Windows"],
        popularidade: "4.8/5",
        licenca: "Proprietária"
    },
    {
        titulo: "Upscayl",
        descricao: "Upscayl é uma ferramenta de aumento de imagem baseada em inteligência artificial que melhora a qualidade e a resolução de imagens. Utiliza técnicas avançadas para tornar suas imagens mais nítidas e detalhadas, sem perda significativa de qualidade.",
        tags: ["Imagem", "Inteligência Artificial", "Edição de Imagem", "Aumento de Resolução", "Melhoria de Qualidade"],
        link: "https://upscayl.org",
        dificuldade: "Fácil",
        preco: "Gratuito",
        plataformas: ["Windows", "Mac", "Linux"],
        popularidade: "4.6/5",
        licenca: "Open Source"
    },
    {
        titulo: "Invoke AI",
        descricao: "Invoke AI é uma plataforma voltada para o desenvolvimento e implementação de soluções baseadas em inteligência artificial. Oferece ferramentas e modelos para criar e treinar modelos de aprendizado de máquina, sendo ideal para desenvolvedores e pesquisadores no campo da IA.",
        tags: ["Inteligência Artificial", "Desenvolvimento", "Machine Learning", "Aprendizado de Máquina", "Modelos"],
        link: "https://login.invoke.ai/u/login/identifier?https://www.invoke.com/",
        dificuldade: "Médio",
        preco: "Freemium",
        plataformas: ["Windows", "Mac", "Linux"],
        popularidade: "4.3/5",
        licenca: "Proprietária"
    },
    {
        titulo: "Proton Mail",
        descricao: "Proton Mail é um serviço de e-mail seguro e criptografado, projetado para proteger a privacidade dos usuários. Oferece uma interface intuitiva e suporte a criptografia de ponta a ponta.",
        tags: ["Email", "Segurança", "Privacidade", "Criptografia", "Proteção de Dados"],
        link: "https://protonmail.com",
        dificuldade: "Fácil",
        preco: "Freemium",
        plataformas: ["Web", "iOS", "Android"],
        popularidade: "4.7/5",
        licenca: "Proprietária"
    },
    {
        titulo: "Proton Drive",
        descricao: "Proton Drive é uma solução de armazenamento em nuvem que garante a segurança e privacidade dos seus arquivos com criptografia de ponta a ponta. Ideal para armazenar e compartilhar documentos de forma segura.",
        tags: ["Armazenamento", "Segurança", "Privacidade", "Criptografia", "Compartilhamento de Arquivos"],
        link: "https://protondrive.com",
        dificuldade: "Fácil",
        preco: "Freemium",
        plataformas: ["Web", "iOS", "Android"],
        popularidade: "4.6/5",
        licenca: "Proprietária"
    },
    {
        titulo: "Cashew",
        descricao: "Cashew é um aplicativo intuitivo de gerenciamento financeiro que ajuda você a controlar suas despesas e receitas de forma simples e eficiente. Com gráficos e relatórios detalhados, você pode visualizar sua saúde financeira em um piscar de olhos.",
        tags: ["Finanças", "Gerenciamento", "Despesas", "Receitas"],
        link: "https://play.google.com/store/search?q=cashew&c=apps&hl=en_US",
        dificuldade: "Médio",
        preco: "Freemium",
        plataformas: ["Web", "iOS", "Android"],
        popularidade: "4.4/5",
        licenca: "Proprietária"
    },
    {
        titulo: "Gesture",
        descricao: "Gesture é um aplicativo que permite controlar seu dispositivo através de gestos personalizados. Oferece uma maneira inovadora de interagir com seu smartphone usando movimentos intuitivos.",
        tags: ["Gestos", "Produtividade", "Controle de Dispositivo", "Interação", "Personalização"],
        link: "https://play.google.com/store/apps/details?id=com.dp.gesture&hl=en_US",
        dificuldade: "Médio",
        preco: "Freemium",
        plataformas: ["iOS", "Android"],
        popularidade: "4.3/5",
        licenca: "Proprietária"
    },
    {
        titulo: "Guess Iron",
        descricao: "Guess Iron é um aplicativo útil para medir e ajustar ângulos e distâncias diretamente no seu celular, transformando-o em uma régua digital. Ideal para quem precisa de uma ferramenta prática de medição em situações do dia a dia.",
        tags: ["Ferramentas", "Medidas", "Utilitário", "Medição", "Régua Digital"],
        link: "https://f-droid.org/packages/de.indie42.guessiron/",
        dificuldade: "Médio",
        preco: "Gratuito",
        plataformas: ["iOS", "Android"],
        popularidade: "4.2/5",
        licenca: "Proprietária"
    },
    {
        titulo: "Stack Overflow",
        descricao: "Stack Overflow é a maior comunidade de perguntas e respostas para desenvolvedores e programadores. É um recurso indispensável para resolver problemas técnicos e encontrar soluções para desafios no desenvolvimento de software, com uma vasta base de conhecimento gerada pela comunidade.",
        tags: ["Desenvolvimento", "Comunidade", "Programação", "Perguntas e Respostas", "Solução de Problemas"],
        link: "https://stackoverflow.com",
        dificuldade: "Fácil",
        preco: "Gratuito",
        plataformas: ["Web"],
        popularidade: "4.8/5",
        licenca: "Proprietária"
    },
    {
        titulo: "Calculator Notification",
        descricao: "Calculator Notification é um aplicativo acessível através do F-Droid que adiciona uma calculadora funcional à sua barra de notificações. Ideal para realizar cálculos rápidos e eficientes sem interromper seu fluxo de trabalho atual.",
        tags: ["Calculadora", "Produtividade", "Utilitário", "Cálculos", "Barra de Notificações"],
        link: "https://f-droid.org/de/packages/com.tananaev.calculator/",
        dificuldade: "Fácil",
        preco: "Gratuito",
        plataformas: ["Android"],
        popularidade: "4.5/5",
        licenca: "Open Source"
    },
    {
        titulo: "NetGuard",
        descricao: "NetGuard é um aplicativo de firewall para Android que oferece controle detalhado sobre o acesso à internet dos aplicativos no seu dispositivo. Ele ajuda a proteger sua privacidade e reduzir o consumo de dados, fornecendo uma interface intuitiva para gerenciar permissões de rede.",
        tags: ["Firewall", "Segurança", "Privacidade", "Controle de Acesso", "Gerenciamento de Permissões"],
        link: "https://www.netguard.me",
        dificuldade: "Médio",
        preco: "Freemium",
        plataformas: ["Android"],
        popularidade: "4.6/5",
        licenca: "Open Source"
    }
];